// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_gcmessages_client_bingo.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMsgClientToGCBingoGetUserDataResponse_EResponse int32

const (
	CMsgClientToGCBingoGetUserDataResponse_k_eInternalError CMsgClientToGCBingoGetUserDataResponse_EResponse = 0
	CMsgClientToGCBingoGetUserDataResponse_k_eSuccess       CMsgClientToGCBingoGetUserDataResponse_EResponse = 1
	CMsgClientToGCBingoGetUserDataResponse_k_eTooBusy       CMsgClientToGCBingoGetUserDataResponse_EResponse = 2
	CMsgClientToGCBingoGetUserDataResponse_k_eDisabled      CMsgClientToGCBingoGetUserDataResponse_EResponse = 3
	CMsgClientToGCBingoGetUserDataResponse_k_eTimeout       CMsgClientToGCBingoGetUserDataResponse_EResponse = 4
)

var CMsgClientToGCBingoGetUserDataResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCBingoGetUserDataResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCBingoGetUserDataResponse_EResponse) Enum() *CMsgClientToGCBingoGetUserDataResponse_EResponse {
	p := new(CMsgClientToGCBingoGetUserDataResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoGetUserDataResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCBingoGetUserDataResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCBingoGetUserDataResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCBingoGetUserDataResponse_EResponse_value, data, "CMsgClientToGCBingoGetUserDataResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoGetUserDataResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCBingoGetUserDataResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{3, 0}
}

type CMsgClientToGCBingoGetStatsDataResponse_EResponse int32

const (
	CMsgClientToGCBingoGetStatsDataResponse_k_eInternalError CMsgClientToGCBingoGetStatsDataResponse_EResponse = 0
	CMsgClientToGCBingoGetStatsDataResponse_k_eSuccess       CMsgClientToGCBingoGetStatsDataResponse_EResponse = 1
	CMsgClientToGCBingoGetStatsDataResponse_k_eTooBusy       CMsgClientToGCBingoGetStatsDataResponse_EResponse = 2
	CMsgClientToGCBingoGetStatsDataResponse_k_eDisabled      CMsgClientToGCBingoGetStatsDataResponse_EResponse = 3
	CMsgClientToGCBingoGetStatsDataResponse_k_eTimeout       CMsgClientToGCBingoGetStatsDataResponse_EResponse = 4
)

var CMsgClientToGCBingoGetStatsDataResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCBingoGetStatsDataResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCBingoGetStatsDataResponse_EResponse) Enum() *CMsgClientToGCBingoGetStatsDataResponse_EResponse {
	p := new(CMsgClientToGCBingoGetStatsDataResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoGetStatsDataResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCBingoGetStatsDataResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCBingoGetStatsDataResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCBingoGetStatsDataResponse_EResponse_value, data, "CMsgClientToGCBingoGetStatsDataResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoGetStatsDataResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCBingoGetStatsDataResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{7, 0}
}

type CMsgClientToGCBingoClaimRowResponse_EResponse int32

const (
	CMsgClientToGCBingoClaimRowResponse_k_eInternalError CMsgClientToGCBingoClaimRowResponse_EResponse = 0
	CMsgClientToGCBingoClaimRowResponse_k_eSuccess       CMsgClientToGCBingoClaimRowResponse_EResponse = 1
	CMsgClientToGCBingoClaimRowResponse_k_eTooBusy       CMsgClientToGCBingoClaimRowResponse_EResponse = 2
	CMsgClientToGCBingoClaimRowResponse_k_eDisabled      CMsgClientToGCBingoClaimRowResponse_EResponse = 3
	CMsgClientToGCBingoClaimRowResponse_k_eTimeout       CMsgClientToGCBingoClaimRowResponse_EResponse = 4
	CMsgClientToGCBingoClaimRowResponse_k_eInvalidRow    CMsgClientToGCBingoClaimRowResponse_EResponse = 5
	CMsgClientToGCBingoClaimRowResponse_k_eExpiredCard   CMsgClientToGCBingoClaimRowResponse_EResponse = 6
)

var CMsgClientToGCBingoClaimRowResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
	5: "k_eInvalidRow",
	6: "k_eExpiredCard",
}

var CMsgClientToGCBingoClaimRowResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
	"k_eInvalidRow":    5,
	"k_eExpiredCard":   6,
}

func (x CMsgClientToGCBingoClaimRowResponse_EResponse) Enum() *CMsgClientToGCBingoClaimRowResponse_EResponse {
	p := new(CMsgClientToGCBingoClaimRowResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoClaimRowResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCBingoClaimRowResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCBingoClaimRowResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCBingoClaimRowResponse_EResponse_value, data, "CMsgClientToGCBingoClaimRowResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoClaimRowResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCBingoClaimRowResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{10, 0}
}

type CMsgClientToGCBingoDevRerollCardResponse_EResponse int32

const (
	CMsgClientToGCBingoDevRerollCardResponse_k_eInternalError CMsgClientToGCBingoDevRerollCardResponse_EResponse = 0
	CMsgClientToGCBingoDevRerollCardResponse_k_eSuccess       CMsgClientToGCBingoDevRerollCardResponse_EResponse = 1
	CMsgClientToGCBingoDevRerollCardResponse_k_eTooBusy       CMsgClientToGCBingoDevRerollCardResponse_EResponse = 2
	CMsgClientToGCBingoDevRerollCardResponse_k_eDisabled      CMsgClientToGCBingoDevRerollCardResponse_EResponse = 3
	CMsgClientToGCBingoDevRerollCardResponse_k_eTimeout       CMsgClientToGCBingoDevRerollCardResponse_EResponse = 4
	CMsgClientToGCBingoDevRerollCardResponse_k_eExpiredCard   CMsgClientToGCBingoDevRerollCardResponse_EResponse = 6
	CMsgClientToGCBingoDevRerollCardResponse_k_eNotAllowed    CMsgClientToGCBingoDevRerollCardResponse_EResponse = 7
)

var CMsgClientToGCBingoDevRerollCardResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
	6: "k_eExpiredCard",
	7: "k_eNotAllowed",
}

var CMsgClientToGCBingoDevRerollCardResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
	"k_eExpiredCard":   6,
	"k_eNotAllowed":    7,
}

func (x CMsgClientToGCBingoDevRerollCardResponse_EResponse) Enum() *CMsgClientToGCBingoDevRerollCardResponse_EResponse {
	p := new(CMsgClientToGCBingoDevRerollCardResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoDevRerollCardResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCBingoDevRerollCardResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCBingoDevRerollCardResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCBingoDevRerollCardResponse_EResponse_value, data, "CMsgClientToGCBingoDevRerollCardResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoDevRerollCardResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCBingoDevRerollCardResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{12, 0}
}

type CMsgBingoSquare struct {
	StatId               *uint32  `protobuf:"varint,1,opt,name=stat_id,json=statId" json:"stat_id,omitempty"`
	StatThreshold        *int32   `protobuf:"varint,2,opt,name=stat_threshold,json=statThreshold" json:"stat_threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgBingoSquare) Reset()         { *m = CMsgBingoSquare{} }
func (m *CMsgBingoSquare) String() string { return proto.CompactTextString(m) }
func (*CMsgBingoSquare) ProtoMessage()    {}
func (*CMsgBingoSquare) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{0}
}

func (m *CMsgBingoSquare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgBingoSquare.Unmarshal(m, b)
}
func (m *CMsgBingoSquare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgBingoSquare.Marshal(b, m, deterministic)
}
func (m *CMsgBingoSquare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgBingoSquare.Merge(m, src)
}
func (m *CMsgBingoSquare) XXX_Size() int {
	return xxx_messageInfo_CMsgBingoSquare.Size(m)
}
func (m *CMsgBingoSquare) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgBingoSquare.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgBingoSquare proto.InternalMessageInfo

func (m *CMsgBingoSquare) GetStatId() uint32 {
	if m != nil && m.StatId != nil {
		return *m.StatId
	}
	return 0
}

func (m *CMsgBingoSquare) GetStatThreshold() int32 {
	if m != nil && m.StatThreshold != nil {
		return *m.StatThreshold
	}
	return 0
}

type CMsgBingoUserData struct {
	Squares              []*CMsgBingoSquare `protobuf:"bytes,1,rep,name=squares" json:"squares,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CMsgBingoUserData) Reset()         { *m = CMsgBingoUserData{} }
func (m *CMsgBingoUserData) String() string { return proto.CompactTextString(m) }
func (*CMsgBingoUserData) ProtoMessage()    {}
func (*CMsgBingoUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{1}
}

func (m *CMsgBingoUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgBingoUserData.Unmarshal(m, b)
}
func (m *CMsgBingoUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgBingoUserData.Marshal(b, m, deterministic)
}
func (m *CMsgBingoUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgBingoUserData.Merge(m, src)
}
func (m *CMsgBingoUserData) XXX_Size() int {
	return xxx_messageInfo_CMsgBingoUserData.Size(m)
}
func (m *CMsgBingoUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgBingoUserData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgBingoUserData proto.InternalMessageInfo

func (m *CMsgBingoUserData) GetSquares() []*CMsgBingoSquare {
	if m != nil {
		return m.Squares
	}
	return nil
}

type CMsgClientToGCBingoGetUserData struct {
	LeagueId             *uint32  `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase          *uint32  `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCBingoGetUserData) Reset()         { *m = CMsgClientToGCBingoGetUserData{} }
func (m *CMsgClientToGCBingoGetUserData) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoGetUserData) ProtoMessage()    {}
func (*CMsgClientToGCBingoGetUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{2}
}

func (m *CMsgClientToGCBingoGetUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoGetUserData.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoGetUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoGetUserData.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoGetUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoGetUserData.Merge(m, src)
}
func (m *CMsgClientToGCBingoGetUserData) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoGetUserData.Size(m)
}
func (m *CMsgClientToGCBingoGetUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoGetUserData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoGetUserData proto.InternalMessageInfo

func (m *CMsgClientToGCBingoGetUserData) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgClientToGCBingoGetUserData) GetLeaguePhase() uint32 {
	if m != nil && m.LeaguePhase != nil {
		return *m.LeaguePhase
	}
	return 0
}

type CMsgClientToGCBingoGetUserDataResponse struct {
	Response             *CMsgClientToGCBingoGetUserDataResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoGetUserDataResponse_EResponse,def=0" json:"response,omitempty"`
	UserData             *CMsgBingoUserData                                `protobuf:"bytes,2,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *CMsgClientToGCBingoGetUserDataResponse) Reset() {
	*m = CMsgClientToGCBingoGetUserDataResponse{}
}
func (m *CMsgClientToGCBingoGetUserDataResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoGetUserDataResponse) ProtoMessage()    {}
func (*CMsgClientToGCBingoGetUserDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{3}
}

func (m *CMsgClientToGCBingoGetUserDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoGetUserDataResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoGetUserDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoGetUserDataResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoGetUserDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoGetUserDataResponse.Merge(m, src)
}
func (m *CMsgClientToGCBingoGetUserDataResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoGetUserDataResponse.Size(m)
}
func (m *CMsgClientToGCBingoGetUserDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoGetUserDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoGetUserDataResponse proto.InternalMessageInfo

const Default_CMsgClientToGCBingoGetUserDataResponse_Response CMsgClientToGCBingoGetUserDataResponse_EResponse = CMsgClientToGCBingoGetUserDataResponse_k_eInternalError

func (m *CMsgClientToGCBingoGetUserDataResponse) GetResponse() CMsgClientToGCBingoGetUserDataResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCBingoGetUserDataResponse_Response
}

func (m *CMsgClientToGCBingoGetUserDataResponse) GetUserData() *CMsgBingoUserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type CMsgBingoIndividualStatData struct {
	StatId               *uint32  `protobuf:"varint,1,opt,name=stat_id,json=statId" json:"stat_id,omitempty"`
	StatValue            *int32   `protobuf:"varint,2,opt,name=stat_value,json=statValue" json:"stat_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgBingoIndividualStatData) Reset()         { *m = CMsgBingoIndividualStatData{} }
func (m *CMsgBingoIndividualStatData) String() string { return proto.CompactTextString(m) }
func (*CMsgBingoIndividualStatData) ProtoMessage()    {}
func (*CMsgBingoIndividualStatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{4}
}

func (m *CMsgBingoIndividualStatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgBingoIndividualStatData.Unmarshal(m, b)
}
func (m *CMsgBingoIndividualStatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgBingoIndividualStatData.Marshal(b, m, deterministic)
}
func (m *CMsgBingoIndividualStatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgBingoIndividualStatData.Merge(m, src)
}
func (m *CMsgBingoIndividualStatData) XXX_Size() int {
	return xxx_messageInfo_CMsgBingoIndividualStatData.Size(m)
}
func (m *CMsgBingoIndividualStatData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgBingoIndividualStatData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgBingoIndividualStatData proto.InternalMessageInfo

func (m *CMsgBingoIndividualStatData) GetStatId() uint32 {
	if m != nil && m.StatId != nil {
		return *m.StatId
	}
	return 0
}

func (m *CMsgBingoIndividualStatData) GetStatValue() int32 {
	if m != nil && m.StatValue != nil {
		return *m.StatValue
	}
	return 0
}

type CMsgBingoStatsData struct {
	StatsData            []*CMsgBingoIndividualStatData `protobuf:"bytes,1,rep,name=stats_data,json=statsData" json:"stats_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CMsgBingoStatsData) Reset()         { *m = CMsgBingoStatsData{} }
func (m *CMsgBingoStatsData) String() string { return proto.CompactTextString(m) }
func (*CMsgBingoStatsData) ProtoMessage()    {}
func (*CMsgBingoStatsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{5}
}

func (m *CMsgBingoStatsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgBingoStatsData.Unmarshal(m, b)
}
func (m *CMsgBingoStatsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgBingoStatsData.Marshal(b, m, deterministic)
}
func (m *CMsgBingoStatsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgBingoStatsData.Merge(m, src)
}
func (m *CMsgBingoStatsData) XXX_Size() int {
	return xxx_messageInfo_CMsgBingoStatsData.Size(m)
}
func (m *CMsgBingoStatsData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgBingoStatsData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgBingoStatsData proto.InternalMessageInfo

func (m *CMsgBingoStatsData) GetStatsData() []*CMsgBingoIndividualStatData {
	if m != nil {
		return m.StatsData
	}
	return nil
}

type CMsgClientToGCBingoGetStatsData struct {
	LeagueId             *uint32  `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase          *uint32  `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCBingoGetStatsData) Reset()         { *m = CMsgClientToGCBingoGetStatsData{} }
func (m *CMsgClientToGCBingoGetStatsData) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoGetStatsData) ProtoMessage()    {}
func (*CMsgClientToGCBingoGetStatsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{6}
}

func (m *CMsgClientToGCBingoGetStatsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoGetStatsData.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoGetStatsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoGetStatsData.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoGetStatsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoGetStatsData.Merge(m, src)
}
func (m *CMsgClientToGCBingoGetStatsData) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoGetStatsData.Size(m)
}
func (m *CMsgClientToGCBingoGetStatsData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoGetStatsData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoGetStatsData proto.InternalMessageInfo

func (m *CMsgClientToGCBingoGetStatsData) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgClientToGCBingoGetStatsData) GetLeaguePhase() uint32 {
	if m != nil && m.LeaguePhase != nil {
		return *m.LeaguePhase
	}
	return 0
}

type CMsgClientToGCBingoGetStatsDataResponse struct {
	Response             *CMsgClientToGCBingoGetStatsDataResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoGetStatsDataResponse_EResponse,def=0" json:"response,omitempty"`
	StatsData            *CMsgBingoStatsData                                `protobuf:"bytes,2,opt,name=stats_data,json=statsData" json:"stats_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *CMsgClientToGCBingoGetStatsDataResponse) Reset() {
	*m = CMsgClientToGCBingoGetStatsDataResponse{}
}
func (m *CMsgClientToGCBingoGetStatsDataResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoGetStatsDataResponse) ProtoMessage()    {}
func (*CMsgClientToGCBingoGetStatsDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{7}
}

func (m *CMsgClientToGCBingoGetStatsDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoGetStatsDataResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoGetStatsDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoGetStatsDataResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoGetStatsDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoGetStatsDataResponse.Merge(m, src)
}
func (m *CMsgClientToGCBingoGetStatsDataResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoGetStatsDataResponse.Size(m)
}
func (m *CMsgClientToGCBingoGetStatsDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoGetStatsDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoGetStatsDataResponse proto.InternalMessageInfo

const Default_CMsgClientToGCBingoGetStatsDataResponse_Response CMsgClientToGCBingoGetStatsDataResponse_EResponse = CMsgClientToGCBingoGetStatsDataResponse_k_eInternalError

func (m *CMsgClientToGCBingoGetStatsDataResponse) GetResponse() CMsgClientToGCBingoGetStatsDataResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCBingoGetStatsDataResponse_Response
}

func (m *CMsgClientToGCBingoGetStatsDataResponse) GetStatsData() *CMsgBingoStatsData {
	if m != nil {
		return m.StatsData
	}
	return nil
}

type CMsgGCToClientBingoUserDataUpdated struct {
	LeagueId             *uint32            `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase          *uint32            `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	UserData             *CMsgBingoUserData `protobuf:"bytes,3,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CMsgGCToClientBingoUserDataUpdated) Reset()         { *m = CMsgGCToClientBingoUserDataUpdated{} }
func (m *CMsgGCToClientBingoUserDataUpdated) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToClientBingoUserDataUpdated) ProtoMessage()    {}
func (*CMsgGCToClientBingoUserDataUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{8}
}

func (m *CMsgGCToClientBingoUserDataUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientBingoUserDataUpdated.Unmarshal(m, b)
}
func (m *CMsgGCToClientBingoUserDataUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientBingoUserDataUpdated.Marshal(b, m, deterministic)
}
func (m *CMsgGCToClientBingoUserDataUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientBingoUserDataUpdated.Merge(m, src)
}
func (m *CMsgGCToClientBingoUserDataUpdated) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientBingoUserDataUpdated.Size(m)
}
func (m *CMsgGCToClientBingoUserDataUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientBingoUserDataUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientBingoUserDataUpdated proto.InternalMessageInfo

func (m *CMsgGCToClientBingoUserDataUpdated) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgGCToClientBingoUserDataUpdated) GetLeaguePhase() uint32 {
	if m != nil && m.LeaguePhase != nil {
		return *m.LeaguePhase
	}
	return 0
}

func (m *CMsgGCToClientBingoUserDataUpdated) GetUserData() *CMsgBingoUserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type CMsgClientToGCBingoClaimRow struct {
	LeagueId             *uint32  `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase          *uint32  `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	RowIndex             *uint32  `protobuf:"varint,3,opt,name=row_index,json=rowIndex" json:"row_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCBingoClaimRow) Reset()         { *m = CMsgClientToGCBingoClaimRow{} }
func (m *CMsgClientToGCBingoClaimRow) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoClaimRow) ProtoMessage()    {}
func (*CMsgClientToGCBingoClaimRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{9}
}

func (m *CMsgClientToGCBingoClaimRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoClaimRow.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoClaimRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoClaimRow.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoClaimRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoClaimRow.Merge(m, src)
}
func (m *CMsgClientToGCBingoClaimRow) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoClaimRow.Size(m)
}
func (m *CMsgClientToGCBingoClaimRow) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoClaimRow.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoClaimRow proto.InternalMessageInfo

func (m *CMsgClientToGCBingoClaimRow) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgClientToGCBingoClaimRow) GetLeaguePhase() uint32 {
	if m != nil && m.LeaguePhase != nil {
		return *m.LeaguePhase
	}
	return 0
}

func (m *CMsgClientToGCBingoClaimRow) GetRowIndex() uint32 {
	if m != nil && m.RowIndex != nil {
		return *m.RowIndex
	}
	return 0
}

type CMsgClientToGCBingoClaimRowResponse struct {
	Response             *CMsgClientToGCBingoClaimRowResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoClaimRowResponse_EResponse,def=0" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *CMsgClientToGCBingoClaimRowResponse) Reset()         { *m = CMsgClientToGCBingoClaimRowResponse{} }
func (m *CMsgClientToGCBingoClaimRowResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoClaimRowResponse) ProtoMessage()    {}
func (*CMsgClientToGCBingoClaimRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{10}
}

func (m *CMsgClientToGCBingoClaimRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoClaimRowResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoClaimRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoClaimRowResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoClaimRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoClaimRowResponse.Merge(m, src)
}
func (m *CMsgClientToGCBingoClaimRowResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoClaimRowResponse.Size(m)
}
func (m *CMsgClientToGCBingoClaimRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoClaimRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoClaimRowResponse proto.InternalMessageInfo

const Default_CMsgClientToGCBingoClaimRowResponse_Response CMsgClientToGCBingoClaimRowResponse_EResponse = CMsgClientToGCBingoClaimRowResponse_k_eInternalError

func (m *CMsgClientToGCBingoClaimRowResponse) GetResponse() CMsgClientToGCBingoClaimRowResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCBingoClaimRowResponse_Response
}

type CMsgClientToGCBingoDevRerollCard struct {
	LeagueId             *uint32  `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase          *uint32  `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCBingoDevRerollCard) Reset()         { *m = CMsgClientToGCBingoDevRerollCard{} }
func (m *CMsgClientToGCBingoDevRerollCard) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoDevRerollCard) ProtoMessage()    {}
func (*CMsgClientToGCBingoDevRerollCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{11}
}

func (m *CMsgClientToGCBingoDevRerollCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoDevRerollCard.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoDevRerollCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoDevRerollCard.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoDevRerollCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoDevRerollCard.Merge(m, src)
}
func (m *CMsgClientToGCBingoDevRerollCard) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoDevRerollCard.Size(m)
}
func (m *CMsgClientToGCBingoDevRerollCard) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoDevRerollCard.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoDevRerollCard proto.InternalMessageInfo

func (m *CMsgClientToGCBingoDevRerollCard) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgClientToGCBingoDevRerollCard) GetLeaguePhase() uint32 {
	if m != nil && m.LeaguePhase != nil {
		return *m.LeaguePhase
	}
	return 0
}

type CMsgClientToGCBingoDevRerollCardResponse struct {
	Response             *CMsgClientToGCBingoDevRerollCardResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoDevRerollCardResponse_EResponse,def=0" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *CMsgClientToGCBingoDevRerollCardResponse) Reset() {
	*m = CMsgClientToGCBingoDevRerollCardResponse{}
}
func (m *CMsgClientToGCBingoDevRerollCardResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCBingoDevRerollCardResponse) ProtoMessage()    {}
func (*CMsgClientToGCBingoDevRerollCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae82d46c92b9373, []int{12}
}

func (m *CMsgClientToGCBingoDevRerollCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCBingoDevRerollCardResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCBingoDevRerollCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCBingoDevRerollCardResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCBingoDevRerollCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCBingoDevRerollCardResponse.Merge(m, src)
}
func (m *CMsgClientToGCBingoDevRerollCardResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCBingoDevRerollCardResponse.Size(m)
}
func (m *CMsgClientToGCBingoDevRerollCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCBingoDevRerollCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCBingoDevRerollCardResponse proto.InternalMessageInfo

const Default_CMsgClientToGCBingoDevRerollCardResponse_Response CMsgClientToGCBingoDevRerollCardResponse_EResponse = CMsgClientToGCBingoDevRerollCardResponse_k_eInternalError

func (m *CMsgClientToGCBingoDevRerollCardResponse) GetResponse() CMsgClientToGCBingoDevRerollCardResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCBingoDevRerollCardResponse_Response
}

func init() {
	proto.RegisterEnum("protocol.CMsgClientToGCBingoGetUserDataResponse_EResponse", CMsgClientToGCBingoGetUserDataResponse_EResponse_name, CMsgClientToGCBingoGetUserDataResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCBingoGetStatsDataResponse_EResponse", CMsgClientToGCBingoGetStatsDataResponse_EResponse_name, CMsgClientToGCBingoGetStatsDataResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCBingoClaimRowResponse_EResponse", CMsgClientToGCBingoClaimRowResponse_EResponse_name, CMsgClientToGCBingoClaimRowResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCBingoDevRerollCardResponse_EResponse", CMsgClientToGCBingoDevRerollCardResponse_EResponse_name, CMsgClientToGCBingoDevRerollCardResponse_EResponse_value)
	proto.RegisterType((*CMsgBingoSquare)(nil), "protocol.CMsgBingoSquare")
	proto.RegisterType((*CMsgBingoUserData)(nil), "protocol.CMsgBingoUserData")
	proto.RegisterType((*CMsgClientToGCBingoGetUserData)(nil), "protocol.CMsgClientToGCBingoGetUserData")
	proto.RegisterType((*CMsgClientToGCBingoGetUserDataResponse)(nil), "protocol.CMsgClientToGCBingoGetUserDataResponse")
	proto.RegisterType((*CMsgBingoIndividualStatData)(nil), "protocol.CMsgBingoIndividualStatData")
	proto.RegisterType((*CMsgBingoStatsData)(nil), "protocol.CMsgBingoStatsData")
	proto.RegisterType((*CMsgClientToGCBingoGetStatsData)(nil), "protocol.CMsgClientToGCBingoGetStatsData")
	proto.RegisterType((*CMsgClientToGCBingoGetStatsDataResponse)(nil), "protocol.CMsgClientToGCBingoGetStatsDataResponse")
	proto.RegisterType((*CMsgGCToClientBingoUserDataUpdated)(nil), "protocol.CMsgGCToClientBingoUserDataUpdated")
	proto.RegisterType((*CMsgClientToGCBingoClaimRow)(nil), "protocol.CMsgClientToGCBingoClaimRow")
	proto.RegisterType((*CMsgClientToGCBingoClaimRowResponse)(nil), "protocol.CMsgClientToGCBingoClaimRowResponse")
	proto.RegisterType((*CMsgClientToGCBingoDevRerollCard)(nil), "protocol.CMsgClientToGCBingoDevRerollCard")
	proto.RegisterType((*CMsgClientToGCBingoDevRerollCardResponse)(nil), "protocol.CMsgClientToGCBingoDevRerollCardResponse")
}

func init() {
	proto.RegisterFile("dota_gcmessages_client_bingo.proto", fileDescriptor_5ae82d46c92b9373)
}

var fileDescriptor_5ae82d46c92b9373 = []byte{
	// 756 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x72, 0x1a, 0x47,
	0x14, 0x0d, 0x28, 0x92, 0xa0, 0x09, 0x68, 0x34, 0x79, 0x48, 0x11, 0x4a, 0x42, 0x26, 0x91, 0xc2,
	0x26, 0xa8, 0x8a, 0x2c, 0xe2, 0x92, 0xbc, 0xb1, 0x40, 0x25, 0xb3, 0xb0, 0xcb, 0x1e, 0x21, 0x2f,
	0xb4, 0x19, 0x37, 0xd3, 0xb7, 0x86, 0x36, 0x3d, 0xd3, 0xb8, 0xbb, 0x07, 0x64, 0xff, 0x81, 0xff,
	0xc0, 0x2b, 0x2f, 0xfc, 0x05, 0xde, 0xf8, 0xff, 0x5c, 0xf3, 0x94, 0xd0, 0x8c, 0x40, 0x2e, 0xca,
	0x2e, 0xaf, 0x98, 0x3e, 0xb7, 0xfb, 0xdc, 0xdb, 0xe7, 0x9c, 0xae, 0x02, 0x19, 0x84, 0x2b, 0x6c,
	0x39, 0xb6, 0x0b, 0x52, 0x62, 0x07, 0xa4, 0x65, 0x33, 0x0a, 0x9e, 0xb2, 0x06, 0xd4, 0x73, 0x78,
	0x6b, 0x2c, 0xb8, 0xe2, 0x7a, 0x29, 0xfc, 0xb1, 0x39, 0xdb, 0xf9, 0x51, 0x2a, 0xc0, 0x6e, 0xb2,
	0x37, 0x2a, 0xef, 0x6c, 0x85, 0x14, 0x72, 0x88, 0x05, 0x10, 0x0b, 0x3c, 0xdf, 0x4d, 0x0a, 0xbb,
	0x19, 0x6e, 0xee, 0xba, 0xdc, 0xbb, 0xad, 0x3a, 0x85, 0x01, 0x1e, 0xd3, 0xb8, 0xfa, 0x8b, 0x63,
	0x4b, 0x32, 0xba, 0x56, 0x8e, 0xf1, 0x9f, 0x07, 0x58, 0x42, 0x0e, 0x0c, 0x36, 0xf7, 0xb2, 0xf0,
	0x6e, 0xfe, 0xed, 0x92, 0x43, 0x13, 0xcc, 0x26, 0x00, 0x97, 0x0a, 0x3c, 0x49, 0xb9, 0x17, 0x1f,
	0x32, 0x9e, 0xa2, 0x8d, 0xce, 0x23, 0xe9, 0x1c, 0x07, 0x0a, 0x9c, 0xbd, 0xf4, 0xb1, 0x00, 0x7d,
	0x0b, 0xad, 0x4b, 0x85, 0x95, 0x45, 0xc9, 0x76, 0xa1, 0x51, 0x68, 0x56, 0xcd, 0xb5, 0x60, 0xd9,
	0x23, 0xfa, 0x1e, 0xaa, 0x85, 0x05, 0x35, 0x14, 0x20, 0x87, 0x9c, 0x91, 0xed, 0x62, 0xa3, 0xd0,
	0x5c, 0x35, 0xab, 0x01, 0xda, 0x4f, 0x40, 0xe3, 0x21, 0xda, 0x4c, 0x29, 0xcf, 0x25, 0x88, 0x2e,
	0x56, 0x58, 0xff, 0x0f, 0xad, 0xcb, 0x90, 0x5e, 0x6e, 0x17, 0x1a, 0x2b, 0xcd, 0x4a, 0xfb, 0xd7,
	0x56, 0x22, 0x74, 0xeb, 0xc6, 0x00, 0x66, 0xb2, 0xd3, 0x78, 0x8e, 0x7e, 0x0f, 0x6a, 0x9d, 0xf0,
	0x1e, 0x7d, 0x7e, 0xda, 0x09, 0x77, 0x9d, 0x82, 0x4a, 0x69, 0xeb, 0xa8, 0xcc, 0x00, 0x3b, 0x3e,
	0x5c, 0x4d, 0x5b, 0x8a, 0x80, 0x1e, 0xd1, 0xff, 0x44, 0x3f, 0xc4, 0xc5, 0xf1, 0x10, 0x4b, 0x08,
	0xa7, 0xad, 0x9a, 0x95, 0x08, 0x7b, 0x12, 0x40, 0xc6, 0x87, 0x22, 0xda, 0x9f, 0xdf, 0xc2, 0x04,
	0x39, 0xe6, 0x9e, 0x04, 0x7d, 0x88, 0x4a, 0x22, 0xfe, 0x0e, 0x3b, 0xd5, 0xda, 0x87, 0xb3, 0x57,
	0x58, 0xcc, 0xd1, 0x3a, 0x49, 0xbe, 0x0e, 0xb5, 0x91, 0x05, 0x3d, 0x4f, 0x81, 0xf0, 0x30, 0x3b,
	0x11, 0x82, 0x0b, 0x33, 0x65, 0xd7, 0xef, 0xa1, 0xb2, 0x2f, 0x41, 0x58, 0x04, 0x2b, 0x1c, 0x0e,
	0x5d, 0x69, 0xd7, 0x73, 0xd4, 0x4a, 0xd9, 0x4b, 0x7e, 0xfc, 0x65, 0x0c, 0x50, 0x39, 0x6d, 0xa1,
	0xff, 0x84, 0x32, 0x4d, 0xb4, 0xef, 0xf4, 0x1a, 0x42, 0x23, 0x0b, 0xce, 0x7c, 0xdb, 0x06, 0x29,
	0xb5, 0x42, 0xbc, 0xee, 0x73, 0x7e, 0xec, 0xcb, 0x57, 0x5a, 0x51, 0xdf, 0x40, 0x95, 0x91, 0x05,
	0x5d, 0x2a, 0xf1, 0x80, 0x01, 0xd1, 0x56, 0x92, 0x0d, 0xd4, 0x05, 0xee, 0x2b, 0xed, 0x7b, 0xe3,
	0x1c, 0xd5, 0xd3, 0x11, 0x7a, 0x1e, 0xa1, 0x13, 0x4a, 0x7c, 0xcc, 0xce, 0x14, 0x56, 0xa1, 0x23,
	0xb7, 0xa6, 0xe7, 0x37, 0x84, 0xc2, 0xc2, 0x04, 0x33, 0x1f, 0xe2, 0xe4, 0x94, 0x03, 0xe4, 0x59,
	0x00, 0x18, 0x17, 0x48, 0xbf, 0xca, 0x81, 0xc2, 0x4a, 0x86, 0x6c, 0xdd, 0xe8, 0x90, 0x8c, 0xb4,
	0x88, 0x92, 0xb3, 0x97, 0xa3, 0x45, 0x76, 0x90, 0x88, 0x3b, 0x64, 0x31, 0x30, 0xfa, 0x23, 0xdf,
	0xa0, 0xab, 0x46, 0xcb, 0x06, 0xe9, 0x63, 0x11, 0xfd, 0xb3, 0xa0, 0x47, 0x6a, 0x0c, 0xcd, 0x24,
	0xe9, 0x68, 0x51, 0x92, 0x32, 0x24, 0x77, 0x8c, 0xd2, 0xd1, 0x8c, 0x7e, 0x51, 0x96, 0x76, 0xf3,
	0x5e, 0x5e, 0xca, 0x7f, 0x4d, 0xb6, 0xaf, 0x91, 0xa6, 0x77, 0x05, 0x64, 0x04, 0x53, 0x9c, 0x76,
	0xfa, 0x3c, 0xba, 0xf6, 0x4c, 0xb6, 0xcf, 0xc7, 0x04, 0x2b, 0x20, 0xcb, 0xda, 0x33, 0xfb, 0xa4,
	0x56, 0x3e, 0xe7, 0x49, 0xbd, 0x8e, 0xe2, 0x7e, 0xc3, 0x92, 0x0e, 0xc3, 0xd4, 0x35, 0xf9, 0x74,
	0xe9, 0xc1, 0xea, 0xa8, 0x2c, 0xf8, 0xd4, 0xa2, 0x1e, 0x81, 0xcb, 0x70, 0xb0, 0xaa, 0x59, 0x12,
	0x7c, 0xda, 0x0b, 0xd6, 0xc6, 0xdb, 0x22, 0xfa, 0x6b, 0x4e, 0xf3, 0xd4, 0x1b, 0xc8, 0x04, 0xea,
	0xff, 0xb9, 0x81, 0xba, 0x49, 0x70, 0xb7, 0x30, 0x19, 0x6f, 0x0a, 0x5f, 0x3e, 0x10, 0xfa, 0x26,
	0xaa, 0x86, 0xb4, 0x13, 0xcc, 0x28, 0x31, 0xf9, 0x54, 0x5b, 0xd5, 0x75, 0x54, 0x1b, 0x59, 0x70,
	0x72, 0x39, 0xa6, 0x02, 0x48, 0x07, 0x0b, 0xa2, 0xad, 0x19, 0x03, 0xd4, 0xc8, 0xb9, 0x58, 0x17,
	0x26, 0x26, 0x08, 0xce, 0x58, 0xb0, 0x6b, 0xe9, 0x37, 0xfd, 0xbe, 0x88, 0x9a, 0x8b, 0x9a, 0xa4,
	0x72, 0xbc, 0xc8, 0x78, 0x70, 0x7f, 0xae, 0x07, 0xb9, 0x2c, 0xdf, 0x92, 0x11, 0x39, 0xaa, 0xc7,
	0xe6, 0x3c, 0xe6, 0xea, 0x01, 0x63, 0x7c, 0x0a, 0x44, 0x5b, 0x3f, 0xde, 0xbf, 0xf8, 0xdb, 0xa1,
	0x6a, 0xe8, 0x0f, 0x5a, 0x36, 0x77, 0x0f, 0xc6, 0x58, 0x60, 0x46, 0xbd, 0x03, 0x87, 0xff, 0x1b,
	0xfc, 0x1b, 0x69, 0x1f, 0x24, 0x12, 0x7c, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x37, 0x88, 0xe3,
	0x7c, 0x09, 0x00, 0x00,
}
