// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_client_enums.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ETournamentTemplate int32

const (
	ETournamentTemplate_k_ETournamentTemplate_None          ETournamentTemplate = 0
	ETournamentTemplate_k_ETournamentTemplate_AutomatedWin3 ETournamentTemplate = 1
)

var ETournamentTemplate_name = map[int32]string{
	0: "k_ETournamentTemplate_None",
	1: "k_ETournamentTemplate_AutomatedWin3",
}

var ETournamentTemplate_value = map[string]int32{
	"k_ETournamentTemplate_None":          0,
	"k_ETournamentTemplate_AutomatedWin3": 1,
}

func (x ETournamentTemplate) Enum() *ETournamentTemplate {
	p := new(ETournamentTemplate)
	*p = x
	return p
}

func (x ETournamentTemplate) String() string {
	return proto.EnumName(ETournamentTemplate_name, int32(x))
}

func (x *ETournamentTemplate) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETournamentTemplate_value, data, "ETournamentTemplate")
	if err != nil {
		return err
	}
	*x = ETournamentTemplate(value)
	return nil
}

func (ETournamentTemplate) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{0}
}

type ETournamentGameState int32

const (
	ETournamentGameState_k_ETournamentGameState_Unknown              ETournamentGameState = 0
	ETournamentGameState_k_ETournamentGameState_Canceled             ETournamentGameState = 1
	ETournamentGameState_k_ETournamentGameState_Scheduled            ETournamentGameState = 2
	ETournamentGameState_k_ETournamentGameState_Active               ETournamentGameState = 3
	ETournamentGameState_k_ETournamentGameState_RadVictory           ETournamentGameState = 20
	ETournamentGameState_k_ETournamentGameState_DireVictory          ETournamentGameState = 21
	ETournamentGameState_k_ETournamentGameState_RadVictoryByForfeit  ETournamentGameState = 22
	ETournamentGameState_k_ETournamentGameState_DireVictoryByForfeit ETournamentGameState = 23
	ETournamentGameState_k_ETournamentGameState_ServerFailure        ETournamentGameState = 40
	ETournamentGameState_k_ETournamentGameState_NotNeeded            ETournamentGameState = 41
)

var ETournamentGameState_name = map[int32]string{
	0:  "k_ETournamentGameState_Unknown",
	1:  "k_ETournamentGameState_Canceled",
	2:  "k_ETournamentGameState_Scheduled",
	3:  "k_ETournamentGameState_Active",
	20: "k_ETournamentGameState_RadVictory",
	21: "k_ETournamentGameState_DireVictory",
	22: "k_ETournamentGameState_RadVictoryByForfeit",
	23: "k_ETournamentGameState_DireVictoryByForfeit",
	40: "k_ETournamentGameState_ServerFailure",
	41: "k_ETournamentGameState_NotNeeded",
}

var ETournamentGameState_value = map[string]int32{
	"k_ETournamentGameState_Unknown":              0,
	"k_ETournamentGameState_Canceled":             1,
	"k_ETournamentGameState_Scheduled":            2,
	"k_ETournamentGameState_Active":               3,
	"k_ETournamentGameState_RadVictory":           20,
	"k_ETournamentGameState_DireVictory":          21,
	"k_ETournamentGameState_RadVictoryByForfeit":  22,
	"k_ETournamentGameState_DireVictoryByForfeit": 23,
	"k_ETournamentGameState_ServerFailure":        40,
	"k_ETournamentGameState_NotNeeded":            41,
}

func (x ETournamentGameState) Enum() *ETournamentGameState {
	p := new(ETournamentGameState)
	*p = x
	return p
}

func (x ETournamentGameState) String() string {
	return proto.EnumName(ETournamentGameState_name, int32(x))
}

func (x *ETournamentGameState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETournamentGameState_value, data, "ETournamentGameState")
	if err != nil {
		return err
	}
	*x = ETournamentGameState(value)
	return nil
}

func (ETournamentGameState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{1}
}

type ETournamentTeamState int32

const (
	ETournamentTeamState_k_ETournamentTeamState_Unknown      ETournamentTeamState = 0
	ETournamentTeamState_k_ETournamentTeamState_Node1        ETournamentTeamState = 1
	ETournamentTeamState_k_ETournamentTeamState_NodeMax      ETournamentTeamState = 1024
	ETournamentTeamState_k_ETournamentTeamState_Eliminated   ETournamentTeamState = 14003
	ETournamentTeamState_k_ETournamentTeamState_Forfeited    ETournamentTeamState = 14004
	ETournamentTeamState_k_ETournamentTeamState_Finished1st  ETournamentTeamState = 15001
	ETournamentTeamState_k_ETournamentTeamState_Finished2nd  ETournamentTeamState = 15002
	ETournamentTeamState_k_ETournamentTeamState_Finished3rd  ETournamentTeamState = 15003
	ETournamentTeamState_k_ETournamentTeamState_Finished4th  ETournamentTeamState = 15004
	ETournamentTeamState_k_ETournamentTeamState_Finished5th  ETournamentTeamState = 15005
	ETournamentTeamState_k_ETournamentTeamState_Finished6th  ETournamentTeamState = 15006
	ETournamentTeamState_k_ETournamentTeamState_Finished7th  ETournamentTeamState = 15007
	ETournamentTeamState_k_ETournamentTeamState_Finished8th  ETournamentTeamState = 15008
	ETournamentTeamState_k_ETournamentTeamState_Finished9th  ETournamentTeamState = 15009
	ETournamentTeamState_k_ETournamentTeamState_Finished10th ETournamentTeamState = 15010
	ETournamentTeamState_k_ETournamentTeamState_Finished11th ETournamentTeamState = 15011
	ETournamentTeamState_k_ETournamentTeamState_Finished12th ETournamentTeamState = 15012
	ETournamentTeamState_k_ETournamentTeamState_Finished13th ETournamentTeamState = 15013
	ETournamentTeamState_k_ETournamentTeamState_Finished14th ETournamentTeamState = 15014
	ETournamentTeamState_k_ETournamentTeamState_Finished15th ETournamentTeamState = 15015
	ETournamentTeamState_k_ETournamentTeamState_Finished16th ETournamentTeamState = 15016
)

var ETournamentTeamState_name = map[int32]string{
	0:     "k_ETournamentTeamState_Unknown",
	1:     "k_ETournamentTeamState_Node1",
	1024:  "k_ETournamentTeamState_NodeMax",
	14003: "k_ETournamentTeamState_Eliminated",
	14004: "k_ETournamentTeamState_Forfeited",
	15001: "k_ETournamentTeamState_Finished1st",
	15002: "k_ETournamentTeamState_Finished2nd",
	15003: "k_ETournamentTeamState_Finished3rd",
	15004: "k_ETournamentTeamState_Finished4th",
	15005: "k_ETournamentTeamState_Finished5th",
	15006: "k_ETournamentTeamState_Finished6th",
	15007: "k_ETournamentTeamState_Finished7th",
	15008: "k_ETournamentTeamState_Finished8th",
	15009: "k_ETournamentTeamState_Finished9th",
	15010: "k_ETournamentTeamState_Finished10th",
	15011: "k_ETournamentTeamState_Finished11th",
	15012: "k_ETournamentTeamState_Finished12th",
	15013: "k_ETournamentTeamState_Finished13th",
	15014: "k_ETournamentTeamState_Finished14th",
	15015: "k_ETournamentTeamState_Finished15th",
	15016: "k_ETournamentTeamState_Finished16th",
}

var ETournamentTeamState_value = map[string]int32{
	"k_ETournamentTeamState_Unknown":      0,
	"k_ETournamentTeamState_Node1":        1,
	"k_ETournamentTeamState_NodeMax":      1024,
	"k_ETournamentTeamState_Eliminated":   14003,
	"k_ETournamentTeamState_Forfeited":    14004,
	"k_ETournamentTeamState_Finished1st":  15001,
	"k_ETournamentTeamState_Finished2nd":  15002,
	"k_ETournamentTeamState_Finished3rd":  15003,
	"k_ETournamentTeamState_Finished4th":  15004,
	"k_ETournamentTeamState_Finished5th":  15005,
	"k_ETournamentTeamState_Finished6th":  15006,
	"k_ETournamentTeamState_Finished7th":  15007,
	"k_ETournamentTeamState_Finished8th":  15008,
	"k_ETournamentTeamState_Finished9th":  15009,
	"k_ETournamentTeamState_Finished10th": 15010,
	"k_ETournamentTeamState_Finished11th": 15011,
	"k_ETournamentTeamState_Finished12th": 15012,
	"k_ETournamentTeamState_Finished13th": 15013,
	"k_ETournamentTeamState_Finished14th": 15014,
	"k_ETournamentTeamState_Finished15th": 15015,
	"k_ETournamentTeamState_Finished16th": 15016,
}

func (x ETournamentTeamState) Enum() *ETournamentTeamState {
	p := new(ETournamentTeamState)
	*p = x
	return p
}

func (x ETournamentTeamState) String() string {
	return proto.EnumName(ETournamentTeamState_name, int32(x))
}

func (x *ETournamentTeamState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETournamentTeamState_value, data, "ETournamentTeamState")
	if err != nil {
		return err
	}
	*x = ETournamentTeamState(value)
	return nil
}

func (ETournamentTeamState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{2}
}

type ETournamentState int32

const (
	ETournamentState_k_ETournamentState_Unknown                     ETournamentState = 0
	ETournamentState_k_ETournamentState_CanceledByAdmin             ETournamentState = 1
	ETournamentState_k_ETournamentState_Completed                   ETournamentState = 2
	ETournamentState_k_ETournamentState_Merged                      ETournamentState = 3
	ETournamentState_k_ETournamentState_ServerFailure               ETournamentState = 4
	ETournamentState_k_ETournamentState_TeamAbandoned               ETournamentState = 5
	ETournamentState_k_ETournamentState_TeamTimeoutForfeit          ETournamentState = 6
	ETournamentState_k_ETournamentState_TeamTimeoutRefund           ETournamentState = 7
	ETournamentState_k_ETournamentState_ServerFailureGrantedVictory ETournamentState = 8
	ETournamentState_k_ETournamentState_TeamTimeoutGrantedVictory   ETournamentState = 9
	ETournamentState_k_ETournamentState_InProgress                  ETournamentState = 100
	ETournamentState_k_ETournamentState_WaitingToMerge              ETournamentState = 101
)

var ETournamentState_name = map[int32]string{
	0:   "k_ETournamentState_Unknown",
	1:   "k_ETournamentState_CanceledByAdmin",
	2:   "k_ETournamentState_Completed",
	3:   "k_ETournamentState_Merged",
	4:   "k_ETournamentState_ServerFailure",
	5:   "k_ETournamentState_TeamAbandoned",
	6:   "k_ETournamentState_TeamTimeoutForfeit",
	7:   "k_ETournamentState_TeamTimeoutRefund",
	8:   "k_ETournamentState_ServerFailureGrantedVictory",
	9:   "k_ETournamentState_TeamTimeoutGrantedVictory",
	100: "k_ETournamentState_InProgress",
	101: "k_ETournamentState_WaitingToMerge",
}

var ETournamentState_value = map[string]int32{
	"k_ETournamentState_Unknown":                     0,
	"k_ETournamentState_CanceledByAdmin":             1,
	"k_ETournamentState_Completed":                   2,
	"k_ETournamentState_Merged":                      3,
	"k_ETournamentState_ServerFailure":               4,
	"k_ETournamentState_TeamAbandoned":               5,
	"k_ETournamentState_TeamTimeoutForfeit":          6,
	"k_ETournamentState_TeamTimeoutRefund":           7,
	"k_ETournamentState_ServerFailureGrantedVictory": 8,
	"k_ETournamentState_TeamTimeoutGrantedVictory":   9,
	"k_ETournamentState_InProgress":                  100,
	"k_ETournamentState_WaitingToMerge":              101,
}

func (x ETournamentState) Enum() *ETournamentState {
	p := new(ETournamentState)
	*p = x
	return p
}

func (x ETournamentState) String() string {
	return proto.EnumName(ETournamentState_name, int32(x))
}

func (x *ETournamentState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETournamentState_value, data, "ETournamentState")
	if err != nil {
		return err
	}
	*x = ETournamentState(value)
	return nil
}

func (ETournamentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{3}
}

type ETournamentNodeState int32

const (
	ETournamentNodeState_k_ETournamentNodeState_Unknown             ETournamentNodeState = 0
	ETournamentNodeState_k_ETournamentNodeState_Canceled            ETournamentNodeState = 1
	ETournamentNodeState_k_ETournamentNodeState_TeamsNotYetAssigned ETournamentNodeState = 2
	ETournamentNodeState_k_ETournamentNodeState_InBetweenGames      ETournamentNodeState = 3
	ETournamentNodeState_k_ETournamentNodeState_GameInProgress      ETournamentNodeState = 4
	ETournamentNodeState_k_ETournamentNodeState_A_Won               ETournamentNodeState = 5
	ETournamentNodeState_k_ETournamentNodeState_B_Won               ETournamentNodeState = 6
	ETournamentNodeState_k_ETournamentNodeState_A_WonByForfeit      ETournamentNodeState = 7
	ETournamentNodeState_k_ETournamentNodeState_B_WonByForfeit      ETournamentNodeState = 8
	ETournamentNodeState_k_ETournamentNodeState_A_Bye               ETournamentNodeState = 9
	ETournamentNodeState_k_ETournamentNodeState_A_Abandoned         ETournamentNodeState = 10
	ETournamentNodeState_k_ETournamentNodeState_ServerFailure       ETournamentNodeState = 11
	ETournamentNodeState_k_ETournamentNodeState_A_TimeoutForfeit    ETournamentNodeState = 12
	ETournamentNodeState_k_ETournamentNodeState_A_TimeoutRefund     ETournamentNodeState = 13
)

var ETournamentNodeState_name = map[int32]string{
	0:  "k_ETournamentNodeState_Unknown",
	1:  "k_ETournamentNodeState_Canceled",
	2:  "k_ETournamentNodeState_TeamsNotYetAssigned",
	3:  "k_ETournamentNodeState_InBetweenGames",
	4:  "k_ETournamentNodeState_GameInProgress",
	5:  "k_ETournamentNodeState_A_Won",
	6:  "k_ETournamentNodeState_B_Won",
	7:  "k_ETournamentNodeState_A_WonByForfeit",
	8:  "k_ETournamentNodeState_B_WonByForfeit",
	9:  "k_ETournamentNodeState_A_Bye",
	10: "k_ETournamentNodeState_A_Abandoned",
	11: "k_ETournamentNodeState_ServerFailure",
	12: "k_ETournamentNodeState_A_TimeoutForfeit",
	13: "k_ETournamentNodeState_A_TimeoutRefund",
}

var ETournamentNodeState_value = map[string]int32{
	"k_ETournamentNodeState_Unknown":             0,
	"k_ETournamentNodeState_Canceled":            1,
	"k_ETournamentNodeState_TeamsNotYetAssigned": 2,
	"k_ETournamentNodeState_InBetweenGames":      3,
	"k_ETournamentNodeState_GameInProgress":      4,
	"k_ETournamentNodeState_A_Won":               5,
	"k_ETournamentNodeState_B_Won":               6,
	"k_ETournamentNodeState_A_WonByForfeit":      7,
	"k_ETournamentNodeState_B_WonByForfeit":      8,
	"k_ETournamentNodeState_A_Bye":               9,
	"k_ETournamentNodeState_A_Abandoned":         10,
	"k_ETournamentNodeState_ServerFailure":       11,
	"k_ETournamentNodeState_A_TimeoutForfeit":    12,
	"k_ETournamentNodeState_A_TimeoutRefund":     13,
}

func (x ETournamentNodeState) Enum() *ETournamentNodeState {
	p := new(ETournamentNodeState)
	*p = x
	return p
}

func (x ETournamentNodeState) String() string {
	return proto.EnumName(ETournamentNodeState_name, int32(x))
}

func (x *ETournamentNodeState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETournamentNodeState_value, data, "ETournamentNodeState")
	if err != nil {
		return err
	}
	*x = ETournamentNodeState(value)
	return nil
}

func (ETournamentNodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{4}
}

type EDOTAGroupMergeResult int32

const (
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_OK                   EDOTAGroupMergeResult = 0
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_FAILED_GENERIC       EDOTAGroupMergeResult = 1
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_NOT_LEADER           EDOTAGroupMergeResult = 2
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_TOO_MANY_PLAYERS     EDOTAGroupMergeResult = 3
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_TOO_MANY_COACHES     EDOTAGroupMergeResult = 4
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_ENGINE_MISMATCH      EDOTAGroupMergeResult = 5
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_NO_SUCH_GROUP        EDOTAGroupMergeResult = 6
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_OTHER_GROUP_NOT_OPEN EDOTAGroupMergeResult = 7
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_ALREADY_INVITED      EDOTAGroupMergeResult = 8
	EDOTAGroupMergeResult_k_EDOTAGroupMergeResult_NOT_INVITED          EDOTAGroupMergeResult = 9
)

var EDOTAGroupMergeResult_name = map[int32]string{
	0: "k_EDOTAGroupMergeResult_OK",
	1: "k_EDOTAGroupMergeResult_FAILED_GENERIC",
	2: "k_EDOTAGroupMergeResult_NOT_LEADER",
	3: "k_EDOTAGroupMergeResult_TOO_MANY_PLAYERS",
	4: "k_EDOTAGroupMergeResult_TOO_MANY_COACHES",
	5: "k_EDOTAGroupMergeResult_ENGINE_MISMATCH",
	6: "k_EDOTAGroupMergeResult_NO_SUCH_GROUP",
	7: "k_EDOTAGroupMergeResult_OTHER_GROUP_NOT_OPEN",
	8: "k_EDOTAGroupMergeResult_ALREADY_INVITED",
	9: "k_EDOTAGroupMergeResult_NOT_INVITED",
}

var EDOTAGroupMergeResult_value = map[string]int32{
	"k_EDOTAGroupMergeResult_OK":                   0,
	"k_EDOTAGroupMergeResult_FAILED_GENERIC":       1,
	"k_EDOTAGroupMergeResult_NOT_LEADER":           2,
	"k_EDOTAGroupMergeResult_TOO_MANY_PLAYERS":     3,
	"k_EDOTAGroupMergeResult_TOO_MANY_COACHES":     4,
	"k_EDOTAGroupMergeResult_ENGINE_MISMATCH":      5,
	"k_EDOTAGroupMergeResult_NO_SUCH_GROUP":        6,
	"k_EDOTAGroupMergeResult_OTHER_GROUP_NOT_OPEN": 7,
	"k_EDOTAGroupMergeResult_ALREADY_INVITED":      8,
	"k_EDOTAGroupMergeResult_NOT_INVITED":          9,
}

func (x EDOTAGroupMergeResult) Enum() *EDOTAGroupMergeResult {
	p := new(EDOTAGroupMergeResult)
	*p = x
	return p
}

func (x EDOTAGroupMergeResult) String() string {
	return proto.EnumName(EDOTAGroupMergeResult_name, int32(x))
}

func (x *EDOTAGroupMergeResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDOTAGroupMergeResult_value, data, "EDOTAGroupMergeResult")
	if err != nil {
		return err
	}
	*x = EDOTAGroupMergeResult(value)
	return nil
}

func (EDOTAGroupMergeResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{5}
}

type EPartyBeaconType int32

const (
	EPartyBeaconType_k_EPartyBeaconType_Available EPartyBeaconType = 0
	EPartyBeaconType_k_EPartyBeaconType_Joinable  EPartyBeaconType = 1
)

var EPartyBeaconType_name = map[int32]string{
	0: "k_EPartyBeaconType_Available",
	1: "k_EPartyBeaconType_Joinable",
}

var EPartyBeaconType_value = map[string]int32{
	"k_EPartyBeaconType_Available": 0,
	"k_EPartyBeaconType_Joinable":  1,
}

func (x EPartyBeaconType) Enum() *EPartyBeaconType {
	p := new(EPartyBeaconType)
	*p = x
	return p
}

func (x EPartyBeaconType) String() string {
	return proto.EnumName(EPartyBeaconType_name, int32(x))
}

func (x *EPartyBeaconType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EPartyBeaconType_value, data, "EPartyBeaconType")
	if err != nil {
		return err
	}
	*x = EPartyBeaconType(value)
	return nil
}

func (EPartyBeaconType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f89df841f51207d9, []int{6}
}

func init() {
	proto.RegisterEnum("protocol.ETournamentTemplate", ETournamentTemplate_name, ETournamentTemplate_value)
	proto.RegisterEnum("protocol.ETournamentGameState", ETournamentGameState_name, ETournamentGameState_value)
	proto.RegisterEnum("protocol.ETournamentTeamState", ETournamentTeamState_name, ETournamentTeamState_value)
	proto.RegisterEnum("protocol.ETournamentState", ETournamentState_name, ETournamentState_value)
	proto.RegisterEnum("protocol.ETournamentNodeState", ETournamentNodeState_name, ETournamentNodeState_value)
	proto.RegisterEnum("protocol.EDOTAGroupMergeResult", EDOTAGroupMergeResult_name, EDOTAGroupMergeResult_value)
	proto.RegisterEnum("protocol.EPartyBeaconType", EPartyBeaconType_name, EPartyBeaconType_value)
}

func init() {
	proto.RegisterFile("dota_client_enums.proto", fileDescriptor_f89df841f51207d9)
}

var fileDescriptor_f89df841f51207d9 = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd7, 0x49, 0x73, 0xdb, 0xb6,
	0x17, 0x00, 0x70, 0x2b, 0x72, 0xbc, 0xe0, 0xff, 0xef, 0xcc, 0x1b, 0x34, 0x69, 0xa6, 0x69, 0xb3,
	0x7a, 0x8d, 0x92, 0xda, 0xb1, 0xdd, 0xf5, 0x48, 0x49, 0xb4, 0xac, 0xd6, 0xa6, 0x3c, 0x12, 0x1d,
	0x8f, 0x7b, 0x28, 0x07, 0x16, 0x5f, 0x44, 0x4c, 0x48, 0x40, 0x43, 0x82, 0x4e, 0x75, 0xeb, 0xd7,
	0xe8, 0xbe, 0xb7, 0xb9, 0xb7, 0xdf, 0xa1, 0x97, 0x7e, 0x8f, 0x5e, 0xfa, 0x21, 0x3a, 0x94, 0x65,
	0x53, 0xe2, 0x22, 0xf3, 0xe4, 0x19, 0xe3, 0x47, 0x10, 0x78, 0xef, 0xe1, 0x41, 0x24, 0xb7, 0x6c,
	0xa9, 0x98, 0xd5, 0x75, 0x39, 0x0a, 0x65, 0xa1, 0x08, 0xbd, 0x60, 0xa3, 0xef, 0x4b, 0x25, 0xe9,
	0xc2, 0xf0, 0x4f, 0x57, 0xba, 0xb7, 0xcf, 0x49, 0xe0, 0x30, 0x1f, 0xed, 0x71, 0x52, 0xf9, 0x8c,
	0xbc, 0xae, 0x9b, 0x32, 0xf4, 0x05, 0xf3, 0x50, 0x28, 0x13, 0xbd, 0xbe, 0xcb, 0x14, 0xd2, 0xbb,
	0xe4, 0xf6, 0x0b, 0x2b, 0x63, 0xc0, 0x32, 0xa4, 0x40, 0x98, 0xa1, 0x6b, 0x64, 0x29, 0x7b, 0x5c,
	0x0b, 0x95, 0xf4, 0x98, 0x42, 0xfb, 0x98, 0x8b, 0x1d, 0x28, 0x55, 0x5e, 0x95, 0xc9, 0x8d, 0x31,
	0xd7, 0x60, 0x1e, 0x76, 0x54, 0xf4, 0x86, 0x87, 0xe4, 0xee, 0xc4, 0x0c, 0x97, 0x23, 0xd6, 0x91,
	0x78, 0x21, 0xe4, 0x4b, 0x01, 0x33, 0x74, 0x89, 0xdc, 0xcb, 0x31, 0x35, 0x26, 0xba, 0xe8, 0xa2,
	0x0d, 0x25, 0xba, 0x4c, 0xee, 0xe7, 0xa0, 0x4e, 0xd7, 0x41, 0x3b, 0x8c, 0xd4, 0x35, 0xfa, 0x80,
	0xdc, 0xc9, 0x51, 0x5a, 0x57, 0xf1, 0x33, 0x84, 0x32, 0x5d, 0x21, 0x0f, 0x72, 0x48, 0x9b, 0xd9,
	0xcf, 0x78, 0x57, 0x49, 0x7f, 0x00, 0x37, 0xe8, 0x2a, 0x79, 0x98, 0xc3, 0xea, 0xdc, 0xc7, 0x0b,
	0x77, 0x93, 0x6e, 0x90, 0xca, 0x95, 0xd3, 0x55, 0x07, 0xbb, 0xd2, 0x7f, 0x8e, 0x5c, 0xc1, 0x1b,
	0x74, 0x93, 0x3c, 0xbe, 0x7a, 0xde, 0xf8, 0x81, 0x5b, 0x74, 0x9d, 0x2c, 0xe7, 0x6d, 0x1c, 0xfd,
	0x33, 0xf4, 0x77, 0x19, 0x77, 0x43, 0x1f, 0x61, 0x7d, 0x4a, 0x88, 0x0c, 0xa9, 0x0c, 0x44, 0x1b,
	0x6d, 0x78, 0x54, 0xf9, 0x67, 0x6e, 0x22, 0x55, 0x26, 0x32, 0x2f, 0x3b, 0x55, 0x97, 0x23, 0x63,
	0xa9, 0xba, 0x4f, 0xde, 0xce, 0x31, 0x86, 0xb4, 0x71, 0x0b, 0x4a, 0x74, 0x29, 0x77, 0x96, 0x48,
	0x1c, 0xb0, 0xcf, 0xe1, 0x8b, 0x05, 0xba, 0x9a, 0xc8, 0x41, 0x8c, 0x74, 0x97, 0x7b, 0x5c, 0x44,
	0x95, 0x05, 0x7f, 0x78, 0x74, 0x25, 0xb1, 0xa3, 0xd8, 0x8d, 0xe2, 0x83, 0x36, 0xfc, 0xe9, 0xd1,
	0xb5, 0x44, 0xae, 0xc6, 0x18, 0x17, 0x3c, 0x70, 0xd0, 0xde, 0x0a, 0x14, 0x7c, 0x19, 0x16, 0x80,
	0xdb, 0xc2, 0x86, 0xaf, 0x8a, 0xc0, 0x1d, 0xdf, 0x86, 0xaf, 0x8b, 0xc0, 0x77, 0x95, 0x03, 0xdf,
	0x14, 0x81, 0xef, 0x29, 0x07, 0xbe, 0x2d, 0x02, 0xdf, 0x57, 0x0e, 0x7c, 0x57, 0x04, 0x7e, 0xa0,
	0x1c, 0xf8, 0xbe, 0x08, 0xfc, 0x50, 0x39, 0xf0, 0x43, 0x11, 0xf8, 0x91, 0x72, 0xe0, 0xc7, 0x90,
	0xae, 0xa7, 0xfa, 0x42, 0x2a, 0xe0, 0x4f, 0x95, 0x03, 0x3f, 0x15, 0x92, 0x5b, 0xca, 0x81, 0x9f,
	0x0b, 0xc9, 0x6d, 0xe5, 0xc0, 0x2f, 0x85, 0xe4, 0x8e, 0x72, 0xe0, 0xd7, 0x42, 0x32, 0x4a, 0xcf,
	0x6f, 0x85, 0x64, 0x94, 0x9f, 0xdf, 0x0b, 0xc9, 0x28, 0x41, 0xaf, 0xc2, 0xca, 0xbf, 0x65, 0x02,
	0x63, 0xf0, 0xfc, 0x94, 0x25, 0x5b, 0x6e, 0xf2, 0x84, 0x25, 0xfb, 0xce, 0x64, 0x23, 0xac, 0x0e,
	0x34, 0xdb, 0xe3, 0x02, 0x4a, 0xa9, 0x93, 0x38, 0x72, 0xd2, 0xeb, 0xbb, 0xa8, 0x86, 0xbd, 0xf0,
	0x0e, 0x79, 0x33, 0x43, 0x1c, 0xa0, 0xdf, 0x43, 0x1b, 0xca, 0xa9, 0x6e, 0x91, 0xd5, 0x53, 0x66,
	0x73, 0x54, 0xb4, 0x67, 0xed, 0x94, 0x09, 0x5b, 0x0a, 0xb4, 0xe1, 0x3a, 0x7d, 0x44, 0x56, 0x72,
	0x94, 0xc9, 0x3d, 0x94, 0xa1, 0xba, 0x68, 0x67, 0x73, 0xa9, 0x76, 0x96, 0xa2, 0x6d, 0x7c, 0x1e,
	0x0a, 0x1b, 0xe6, 0xe9, 0x36, 0xd9, 0xb8, 0x6a, 0x81, 0x0d, 0x9f, 0x09, 0x85, 0x97, 0x5d, 0x7b,
	0x81, 0x3e, 0x25, 0x4f, 0xa6, 0xcf, 0x9e, 0x78, 0x62, 0x31, 0x75, 0x63, 0x9c, 0x3f, 0xd1, 0x14,
	0x87, 0xbe, 0xec, 0xf9, 0x18, 0x04, 0x60, 0xa7, 0x6e, 0x8c, 0x73, 0x72, 0xcc, 0xb8, 0xe2, 0xa2,
	0x67, 0xca, 0x61, 0x44, 0x01, 0x2b, 0x7f, 0xcf, 0x4e, 0x34, 0xd6, 0xa8, 0xdd, 0x65, 0x37, 0xd6,
	0xcb, 0x91, 0x29, 0x77, 0x60, 0x6c, 0xc6, 0xee, 0xc0, 0xe4, 0x5d, 0x13, 0xa3, 0x68, 0x87, 0x81,
	0x21, 0xd5, 0x09, 0x2a, 0x2d, 0x08, 0x78, 0x4f, 0x0c, 0x2b, 0x20, 0x99, 0x96, 0xd8, 0x37, 0x45,
	0x15, 0xd5, 0x4b, 0x44, 0x11, 0xdd, 0x11, 0x01, 0x94, 0xa7, 0xd0, 0x48, 0x8c, 0x85, 0x63, 0x36,
	0x55, 0x79, 0x31, 0xd5, 0xac, 0x63, 0x29, 0xe0, 0xfa, 0x14, 0x51, 0x1d, 0x8a, 0xb9, 0x29, 0xaf,
	0x1b, 0xce, 0x11, 0xdf, 0x7f, 0xf3, 0x53, 0x68, 0x75, 0x92, 0x2e, 0x4c, 0x5d, 0x59, 0x75, 0x80,
	0xb0, 0x98, 0x3a, 0x5d, 0xe3, 0x22, 0x2e, 0x68, 0x92, 0xaa, 0xd2, 0xd8, 0x4d, 0x1e, 0x90, 0xff,
	0xd1, 0xc7, 0x64, 0x2d, 0x77, 0xc6, 0x44, 0xf1, 0xff, 0x9f, 0x56, 0xc8, 0xea, 0x55, 0x78, 0x54,
	0xfe, 0xaf, 0x55, 0xfe, 0x2a, 0x93, 0x9b, 0x7a, 0xbd, 0x65, 0x6a, 0x0d, 0x5f, 0x86, 0xfd, 0x61,
	0x91, 0xb5, 0x31, 0x08, 0x5d, 0x35, 0x6a, 0x21, 0x59, 0x43, 0x56, 0xeb, 0x13, 0x98, 0x19, 0xbd,
	0x25, 0x73, 0x7c, 0x57, 0x6b, 0xee, 0xeb, 0x75, 0xab, 0xa1, 0x1b, 0x7a, 0xbb, 0x59, 0x83, 0xd2,
	0x28, 0x20, 0x99, 0xd6, 0x68, 0x99, 0xd6, 0xbe, 0xae, 0xd5, 0xf5, 0x36, 0x5c, 0xa3, 0x4f, 0xc8,
	0x7a, 0x9e, 0x33, 0x5b, 0x2d, 0xeb, 0x40, 0x33, 0x4e, 0xac, 0xc3, 0x7d, 0xed, 0x44, 0x6f, 0x77,
	0xa0, 0x5c, 0x48, 0xd7, 0x5a, 0x5a, 0x6d, 0x4f, 0xef, 0xc0, 0xec, 0x28, 0x84, 0x99, 0x5a, 0x37,
	0x1a, 0x4d, 0x43, 0xb7, 0x0e, 0x9a, 0x9d, 0x03, 0xcd, 0xac, 0xed, 0x5d, 0xb6, 0x9a, 0x9c, 0x05,
	0x5b, 0x9d, 0xa3, 0xda, 0x9e, 0xd5, 0x68, 0xb7, 0x8e, 0x0e, 0x61, 0x6e, 0xd4, 0x0c, 0xb2, 0xe3,
	0x64, 0xee, 0xe9, 0xed, 0x73, 0x38, 0xdc, 0x67, 0xeb, 0x50, 0x37, 0x60, 0x7e, 0xda, 0x4a, 0xb4,
	0xfd, 0xb6, 0xae, 0xd5, 0x4f, 0xac, 0xa6, 0xf1, 0xac, 0x69, 0xea, 0x75, 0x58, 0x18, 0xfd, 0x38,
	0xce, 0x0d, 0xdd, 0x05, 0x5c, 0xac, 0x1c, 0x11, 0xd0, 0x0f, 0x99, 0xaf, 0x06, 0x55, 0x64, 0x5d,
	0x29, 0xcc, 0x41, 0x1f, 0x47, 0xa5, 0x9a, 0xf8, 0xaf, 0xa5, 0x9d, 0x31, 0xee, 0xb2, 0x53, 0x37,
	0xfa, 0xed, 0x7d, 0x8f, 0xbc, 0x95, 0x21, 0x3e, 0x96, 0x5c, 0x0c, 0x41, 0xa9, 0xba, 0xfa, 0xe9,
	0x72, 0x8f, 0x2b, 0x27, 0x3c, 0xdd, 0xe8, 0x4a, 0x6f, 0xb3, 0xcf, 0x7c, 0xe6, 0x72, 0xb1, 0xd9,
	0x93, 0xef, 0x44, 0x1f, 0x01, 0xdb, 0x9b, 0x17, 0x1f, 0x05, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x69, 0xa2, 0x86, 0x51, 0x38, 0x0c, 0x00, 0x00,
}
