// Code generated by protoc-gen-go. DO NOT EDIT.
// source: econ_shared_enums.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EGCEconBaseMsg int32

const (
	EGCEconBaseMsg_k_EMsgGCGenericResult EGCEconBaseMsg = 2579
)

var EGCEconBaseMsg_name = map[int32]string{
	2579: "k_EMsgGCGenericResult",
}

var EGCEconBaseMsg_value = map[string]int32{
	"k_EMsgGCGenericResult": 2579,
}

func (x EGCEconBaseMsg) Enum() *EGCEconBaseMsg {
	p := new(EGCEconBaseMsg)
	*p = x
	return p
}

func (x EGCEconBaseMsg) String() string {
	return proto.EnumName(EGCEconBaseMsg_name, int32(x))
}

func (x *EGCEconBaseMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCEconBaseMsg_value, data, "EGCEconBaseMsg")
	if err != nil {
		return err
	}
	*x = EGCEconBaseMsg(value)
	return nil
}

func (EGCEconBaseMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df63e448fc286698, []int{0}
}

type EGCMsgResponse int32

const (
	EGCMsgResponse_k_EGCMsgResponseOK           EGCMsgResponse = 0
	EGCMsgResponse_k_EGCMsgResponseDenied       EGCMsgResponse = 1
	EGCMsgResponse_k_EGCMsgResponseServerError  EGCMsgResponse = 2
	EGCMsgResponse_k_EGCMsgResponseTimeout      EGCMsgResponse = 3
	EGCMsgResponse_k_EGCMsgResponseInvalid      EGCMsgResponse = 4
	EGCMsgResponse_k_EGCMsgResponseNoMatch      EGCMsgResponse = 5
	EGCMsgResponse_k_EGCMsgResponseUnknownError EGCMsgResponse = 6
	EGCMsgResponse_k_EGCMsgResponseNotLoggedOn  EGCMsgResponse = 7
	EGCMsgResponse_k_EGCMsgFailedToCreate       EGCMsgResponse = 8
)

var EGCMsgResponse_name = map[int32]string{
	0: "k_EGCMsgResponseOK",
	1: "k_EGCMsgResponseDenied",
	2: "k_EGCMsgResponseServerError",
	3: "k_EGCMsgResponseTimeout",
	4: "k_EGCMsgResponseInvalid",
	5: "k_EGCMsgResponseNoMatch",
	6: "k_EGCMsgResponseUnknownError",
	7: "k_EGCMsgResponseNotLoggedOn",
	8: "k_EGCMsgFailedToCreate",
}

var EGCMsgResponse_value = map[string]int32{
	"k_EGCMsgResponseOK":           0,
	"k_EGCMsgResponseDenied":       1,
	"k_EGCMsgResponseServerError":  2,
	"k_EGCMsgResponseTimeout":      3,
	"k_EGCMsgResponseInvalid":      4,
	"k_EGCMsgResponseNoMatch":      5,
	"k_EGCMsgResponseUnknownError": 6,
	"k_EGCMsgResponseNotLoggedOn":  7,
	"k_EGCMsgFailedToCreate":       8,
}

func (x EGCMsgResponse) Enum() *EGCMsgResponse {
	p := new(EGCMsgResponse)
	*p = x
	return p
}

func (x EGCMsgResponse) String() string {
	return proto.EnumName(EGCMsgResponse_name, int32(x))
}

func (x *EGCMsgResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgResponse_value, data, "EGCMsgResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgResponse(value)
	return nil
}

func (EGCMsgResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df63e448fc286698, []int{1}
}

type EGCMsgUseItemResponse int32

const (
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed                    EGCMsgUseItemResponse = 0
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_GiftNoOtherPlayers          EGCMsgUseItemResponse = 1
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ServerError                 EGCMsgUseItemResponse = 2
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_MiniGameAlreadyStarted      EGCMsgUseItemResponse = 3
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted       EGCMsgUseItemResponse = 4
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted EGCMsgUseItemResponse = 5
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_NotInLowPriorityPool        EGCMsgUseItemResponse = 6
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_NotHighEnoughLevel          EGCMsgUseItemResponse = 7
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EventNotActive              EGCMsgUseItemResponse = 8
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted EGCMsgUseItemResponse = 9
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_MissingRequirement          EGCMsgUseItemResponse = 10
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew        EGCMsgUseItemResponse = 11
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EmoticonUnlock_Complete     EGCMsgUseItemResponse = 12
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_Compendium         EGCMsgUseItemResponse = 13
)

var EGCMsgUseItemResponse_name = map[int32]string{
	0:  "k_EGCMsgUseItemResponse_ItemUsed",
	1:  "k_EGCMsgUseItemResponse_GiftNoOtherPlayers",
	2:  "k_EGCMsgUseItemResponse_ServerError",
	3:  "k_EGCMsgUseItemResponse_MiniGameAlreadyStarted",
	4:  "k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted",
	5:  "k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted",
	6:  "k_EGCMsgUseItemResponse_NotInLowPriorityPool",
	7:  "k_EGCMsgUseItemResponse_NotHighEnoughLevel",
	8:  "k_EGCMsgUseItemResponse_EventNotActive",
	9:  "k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted",
	10: "k_EGCMsgUseItemResponse_MissingRequirement",
	11: "k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew",
	12: "k_EGCMsgUseItemResponse_EmoticonUnlock_Complete",
	13: "k_EGCMsgUseItemResponse_ItemUsed_Compendium",
}

var EGCMsgUseItemResponse_value = map[string]int32{
	"k_EGCMsgUseItemResponse_ItemUsed":                    0,
	"k_EGCMsgUseItemResponse_GiftNoOtherPlayers":          1,
	"k_EGCMsgUseItemResponse_ServerError":                 2,
	"k_EGCMsgUseItemResponse_MiniGameAlreadyStarted":      3,
	"k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted":       4,
	"k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted": 5,
	"k_EGCMsgUseItemResponse_NotInLowPriorityPool":        6,
	"k_EGCMsgUseItemResponse_NotHighEnoughLevel":          7,
	"k_EGCMsgUseItemResponse_EventNotActive":              8,
	"k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted": 9,
	"k_EGCMsgUseItemResponse_MissingRequirement":          10,
	"k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew":        11,
	"k_EGCMsgUseItemResponse_EmoticonUnlock_Complete":     12,
	"k_EGCMsgUseItemResponse_ItemUsed_Compendium":         13,
}

func (x EGCMsgUseItemResponse) Enum() *EGCMsgUseItemResponse {
	p := new(EGCMsgUseItemResponse)
	*p = x
	return p
}

func (x EGCMsgUseItemResponse) String() string {
	return proto.EnumName(EGCMsgUseItemResponse_name, int32(x))
}

func (x *EGCMsgUseItemResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgUseItemResponse_value, data, "EGCMsgUseItemResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgUseItemResponse(value)
	return nil
}

func (EGCMsgUseItemResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df63e448fc286698, []int{2}
}

type CMsgGenericResult struct {
	Eresult              *uint32  `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	DebugMessage         *string  `protobuf:"bytes,2,opt,name=debug_message,json=debugMessage" json:"debug_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGenericResult) Reset()         { *m = CMsgGenericResult{} }
func (m *CMsgGenericResult) String() string { return proto.CompactTextString(m) }
func (*CMsgGenericResult) ProtoMessage()    {}
func (*CMsgGenericResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_df63e448fc286698, []int{0}
}

func (m *CMsgGenericResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGenericResult.Unmarshal(m, b)
}
func (m *CMsgGenericResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGenericResult.Marshal(b, m, deterministic)
}
func (m *CMsgGenericResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGenericResult.Merge(m, src)
}
func (m *CMsgGenericResult) XXX_Size() int {
	return xxx_messageInfo_CMsgGenericResult.Size(m)
}
func (m *CMsgGenericResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGenericResult.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGenericResult proto.InternalMessageInfo

const Default_CMsgGenericResult_Eresult uint32 = 2

func (m *CMsgGenericResult) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgGenericResult_Eresult
}

func (m *CMsgGenericResult) GetDebugMessage() string {
	if m != nil && m.DebugMessage != nil {
		return *m.DebugMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.EGCEconBaseMsg", EGCEconBaseMsg_name, EGCEconBaseMsg_value)
	proto.RegisterEnum("protocol.EGCMsgResponse", EGCMsgResponse_name, EGCMsgResponse_value)
	proto.RegisterEnum("protocol.EGCMsgUseItemResponse", EGCMsgUseItemResponse_name, EGCMsgUseItemResponse_value)
	proto.RegisterType((*CMsgGenericResult)(nil), "protocol.CMsgGenericResult")
}

func init() {
	proto.RegisterFile("econ_shared_enums.proto", fileDescriptor_df63e448fc286698)
}

var fileDescriptor_df63e448fc286698 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x26, 0xfc, 0xb3, 0x85, 0x6a, 0xbb, 0x2a, 0x3f, 0x82, 0x4a, 0x8d, 0x0a, 0xa2, 0x28, 0x85,
	0xa4, 0x85, 0x43, 0xa5, 0xde, 0x20, 0xb8, 0x29, 0x2a, 0x36, 0x51, 0x20, 0x97, 0x5e, 0xac, 0xc5,
	0x9e, 0x3a, 0xab, 0xd8, 0x33, 0xe9, 0xee, 0x38, 0x88, 0xe7, 0xe8, 0xb1, 0xcf, 0xd3, 0xf7, 0xaa,
	0x12, 0x1a, 0x54, 0x22, 0x1c, 0x7a, 0xf2, 0xf8, 0xfb, 0xd1, 0x37, 0xdf, 0x1c, 0x56, 0xac, 0x43,
	0x44, 0x18, 0xba, 0x8e, 0xb6, 0x10, 0x87, 0x80, 0x79, 0xe6, 0xaa, 0x3d, 0x4b, 0x4c, 0x6a, 0x71,
	0xf8, 0x89, 0x28, 0x7d, 0xd3, 0x16, 0x2f, 0xea, 0xbe, 0x4b, 0x1a, 0x80, 0x60, 0x4d, 0xd4, 0x02,
	0x97, 0xa7, 0xac, 0xb6, 0xc4, 0x02, 0xd8, 0xe1, 0xb8, 0x51, 0x2a, 0x97, 0xf6, 0x56, 0x3e, 0x95,
	0x0e, 0x5b, 0x23, 0x44, 0x6d, 0x8b, 0x95, 0x18, 0xae, 0xf3, 0x24, 0xcc, 0xc0, 0x39, 0x9d, 0xc0,
	0xc6, 0x74, 0xb9, 0xb4, 0xb7, 0xd4, 0x5a, 0x1e, 0x82, 0xfe, 0x1d, 0x56, 0xd9, 0x17, 0xcf, 0xbd,
	0x46, 0xdd, 0x8b, 0x08, 0x4f, 0xb4, 0x03, 0xdf, 0x25, 0x6a, 0x53, 0xac, 0x76, 0x43, 0x6f, 0x10,
	0x55, 0x7f, 0x10, 0x26, 0x7f, 0xbe, 0xac, 0xfc, 0x9a, 0x1e, 0xca, 0x7d, 0x97, 0xb4, 0xc0, 0xf5,
	0x08, 0x1d, 0xa8, 0x35, 0xa1, 0xba, 0xe1, 0x43, 0xec, 0xe2, 0xab, 0x9c, 0x52, 0x9b, 0x62, 0x6d,
	0x1c, 0x3f, 0x05, 0x34, 0x10, 0xcb, 0x92, 0x7a, 0x2d, 0xb6, 0xc6, 0xb9, 0x4b, 0xb0, 0x7d, 0xb0,
	0x9e, 0xb5, 0x64, 0xe5, 0xb4, 0xda, 0x12, 0xeb, 0xe3, 0x82, 0x2b, 0x93, 0x01, 0xe5, 0x2c, 0x67,
	0x1e, 0x23, 0xcf, 0xb0, 0xaf, 0x53, 0x13, 0xcb, 0xd9, 0xc7, 0xc8, 0x80, 0x7c, 0xcd, 0x51, 0x47,
	0xce, 0xa9, 0xb2, 0x78, 0x35, 0x4e, 0xb6, 0xb1, 0x8b, 0x74, 0x83, 0x77, 0xc1, 0xf3, 0x8f, 0x6d,
	0x16, 0x10, 0x9f, 0x53, 0x92, 0x40, 0x7c, 0x81, 0x72, 0xe1, 0xdf, 0x5a, 0x9f, 0xb5, 0x49, 0x21,
	0xbe, 0xa2, 0xba, 0x05, 0xcd, 0x20, 0x17, 0x2b, 0xbf, 0xe7, 0xc4, 0xea, 0x1d, 0xd5, 0x76, 0x70,
	0xc6, 0x90, 0xdd, 0x1f, 0x69, 0x47, 0x94, 0x47, 0xae, 0x31, 0x2a, 0x1c, 0xfc, 0xb4, 0x1d, 0xc4,
	0x72, 0x4a, 0x55, 0x45, 0xa5, 0x48, 0xd5, 0x30, 0xdf, 0x39, 0xa0, 0x0b, 0xee, 0x80, 0x6d, 0xa6,
	0xfa, 0x16, 0xac, 0x93, 0x25, 0xf5, 0x56, 0x6c, 0x17, 0xe9, 0x1f, 0x9e, 0xf3, 0x50, 0x54, 0x8b,
	0x84, 0xbe, 0x41, 0xd3, 0xd0, 0x19, 0x1c, 0xa7, 0x16, 0x74, 0x7c, 0x7b, 0xc9, 0xda, 0x32, 0xc4,
	0x72, 0x46, 0x7d, 0x10, 0x07, 0x4f, 0xad, 0x3c, 0x1c, 0x5c, 0xc3, 0x6a, 0x1c, 0x58, 0x66, 0xd5,
	0x47, 0x71, 0x54, 0x64, 0x39, 0xb5, 0xd4, 0x6b, 0x69, 0x86, 0x13, 0xc2, 0xdc, 0xfd, 0xcd, 0x1a,
	0x19, 0xe7, 0xd4, 0x7b, 0xb1, 0x5f, 0x64, 0x0c, 0x88, 0xcf, 0xf0, 0x9c, 0x6e, 0x9a, 0xd6, 0x90,
	0x35, 0x7c, 0xdb, 0x24, 0x4a, 0xe5, 0xfc, 0xa4, 0x53, 0x05, 0xc4, 0x5f, 0x4c, 0xd2, 0xf1, 0x90,
	0xf2, 0xa4, 0x73, 0x0e, 0x7d, 0x48, 0xe5, 0x82, 0xaa, 0x88, 0xdd, 0x22, 0xbd, 0xd7, 0x07, 0xe4,
	0x80, 0xf8, 0x38, 0x62, 0xd3, 0x07, 0xb9, 0x38, 0xa9, 0xc6, 0x7d, 0xf3, 0xa1, 0xa9, 0x49, 0x06,
	0xf9, 0xbe, 0xff, 0xd2, 0xa4, 0xa5, 0x7c, 0xe3, 0x9c, 0xc1, 0xa4, 0x05, 0x3f, 0x72, 0x63, 0x21,
	0x03, 0x64, 0x29, 0x26, 0xd5, 0xf6, 0x32, 0x62, 0x13, 0x11, 0xb6, 0x31, 0xa5, 0xa8, 0x1b, 0x06,
	0x14, 0xc0, 0x8d, 0x7c, 0xa6, 0x8e, 0x44, 0xed, 0x3f, 0x1d, 0x75, 0xca, 0x7a, 0x29, 0x30, 0xc8,
	0x65, 0x55, 0x13, 0xef, 0x9e, 0xec, 0x33, 0x90, 0x03, 0xc6, 0x26, 0xcf, 0xe4, 0xca, 0xc9, 0xee,
	0xb7, 0x9d, 0xc4, 0x70, 0x27, 0xbf, 0xae, 0x46, 0x94, 0xd5, 0x7a, 0xda, 0xea, 0xd4, 0x60, 0x2d,
	0xa1, 0x83, 0x98, 0x58, 0x1f, 0xd6, 0x46, 0x4f, 0xd2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23,
	0xe5, 0x29, 0x26, 0xb6, 0x04, 0x00, 0x00,
}
